let data = [
    {
        "name" : "Life of Pi",
        "author": "Yann Martel",
        "url": "./images/Life of Pi.png",
        "date": "08/07/22",
        "rating": "8",
        "review": "https://tomasmiskov.com/life-of-pi.html",
    },
    {
        "name" : "A Man Called Ove",
        "author": "Frederik Backman",
        "url": "./images/A Man Called Ove.png",
        "date": "27/12/21",
        "rating": "7",
        "review": "https://tomasmiskov.com/a-man-called-ove.html",
    },
    {
        "name" : "The Unlikely Pilgrimage of Harold Fry",
        "author": "Rachel Joyce",
        "url": "./images/The Unlikely Pilgrimage of Harold Fry.png", 
        "date": "21/07/22",
        "rating": "6",
        "review": "https://tomasmiskov.com/the-unlikely-pilgrimage-of-harold-fry.html",
    },
    {
        "name" : "Neophilia",
        "author": "Lyall Watson",
        "url": "./images/Neophilia.png", 
        "date": "20/08/22",
        "rating": "8",
        "review": "https://tomasmiskov.com/neophilia.html",
    },
    {
        "name" : "A Thousand Splendid Suns",
        "author": "Khaled Hossein",
        "url": "./images/A Thousand Splendid Suns.png", 
        "date": "30/07/22",
        "rating": "10",
        "review": "https://tomasmiskov.com/a-thousand-splendid-suns.html",
    },
    {
        "name" : "Animal Farm",
        "author": "George Orwell",
        "url": "./images/Animal Farm.png", 
        "date": "15/08/21",
        "rating": "8",
        "review": "https://tomasmiskov.com/animal-farm.html",
    },
    {
        "name" : "The Da Vinci Code",
        "author": "Dan Brown",
        "url": "./images/The Da Vinci Code.png", 
        "date": "13/08/22",
        "rating": "9",
        "review": "https://tomasmiskov.com/the-da-vinci-code.html",
    },
    {
        "name" : "The Pleasure of Finding Things Out",
        "author": "Richard P. Feynman",
        "url": "./images/The Pleasure of Finding Things Out.png", 
        "date": "25/05/22",
        "rating": "9",
        "review": "https://tomasmiskov.com/the-pleasure-of-finding-things-out.html",
    },
    {
        "name" : "Oscar and the Lady in Pink",
        "author": "Éric-Emmanuel Schmitt",
        "url": "./images/Oscar and the Lady in Pink.png", 
        "date": "24/08/21",
        "rating": "8",
        "review": "https://tomasmiskov.com/oscar-and-the-lady-in-pink.html",
    },
    {
        "name" : "Skin in the Game",
        "author": "Nassim Nicholas Taleb",
        "url": "./images/Skin in the Game.png", 
        "date": "12/06/20",
        "rating": "6",
        "review": "https://tomasmiskov.com/skin-in-the-game.html",
    },
    // {
    //     "name" : "Siddhartha",
    //     "author": "Hermann Hesse",
    //     "url": "./images/E-reader.png", 
    //     "date": "12/07/21",
    //     "rating": "6",
    //     "review": "https://tomasmiskov.com/siddhartha.html",
    // },
    {
        "name" : "Flowers for Algernon",
        "author": "Daniel Keyes",
        "url": "./images/Flowers for Algernon.png",  
        "date": "28/07/21",
        "rating": "10",
        "review": "https://tomasmiskov.com/flowers-for-algernon.html",
    },
    // {
    //     "name" : "Ten Little Soldiers",
    //     "author": "Agatha Christie",
    //     "url": "./images/E-reader.png",  
    //     "date": "31/07/21",
    //     "rating": "9",
    //     "review": "https://tomasmiskov.com/ten-little-soldiers.html",
    // },
    {
        "name" : "The Schopenhauer Cure",
        "author": "Irvin D. Yalom",
        "url":  "./images/The Schopenhauer Cure.png",  
        "date": "10/01/22",
        "rating": "7",
        "review": "https://tomasmiskov.com/the-schopenhauer-cure.html",
    },
    {
        "name" : "The Minds of Billy Milligan",
        "author": "Daniel Keyes",
        "url":  "./images/The Minds of Billy Milligan.png",  
        "date": "11/09/22",
        "rating": "7",
        "review": "https://tomasmiskov.com/the-minds-of-billy-milligan.html",
    },
    {
        "name" : "The End of Everything",
        "author": "Dr. Katherine (Katie) Mack",
        "url":  "./images/The End of Everything.png",  
        "date": "28/09/22",
        "rating": "8.5",
        "review": "https://tomasmiskov.com/the-end-of-everything.html",
    },
    {
        "name" : "Perfectly Reasonable Deviations from the Beaten Track",
        "author": "Richard P. and Michelle Feynman",
        "url":  "./images/Perfectly Reasonable Deviations.png",  
        "date": "13/11/22",
        "rating": "8.5",
        "review": "https://tomasmiskov.com/perfectly-reasonable-deviations.html",
    },
    {
        "name" : "The Amazing Story of the Man Who Cycled from India to Europe for Love",
        "author": "Per J. Andersson, Anna Holmwood (Translation)",
        "url":  "./images/The Amazing Story.png",  
        "date": "28/02/23",
        "rating": "7",
        "review": "https://tomasmiskov.com/the-amazing-story.html",
    },
    {
        "name" : "The Stranger",
        "author": "Albert Camus",
        "url":  "./images/The Stranger.png",  
        "date": "08/03/23",
        "rating": "6",
        "review": "https://tomasmiskov.com/the-stranger.html",
    },
    {
        "name" : "Anxious People",
        "author": "Frederik Backman",
        "url":  "./images/Anxious People.png",  
        "date": "21/04/23",
        "rating": "8",
        "review": "https://tomasmiskov.com/anxious-people.html",
    },
    {
        "name" : "Helgoland",
        "author": "Carlo Rovelli",
        "url":  "./images/Helgoland.png",  
        "date": "29/05/23",
        "rating": "8",
        "review": "https://tomasmiskov.com/helgoland.html",
    },
    {
        "name" : "Zero - The Biography of a Dangerous Idea",
        "author": "Charles Seife",
        "url":  "./images/Zero.png",  
        "date": "10/06/23",
        "rating": "8",
        "review": "https://tomasmiskov.com/zero.html",
    },
    {
        "name" : "Papillon",
        "author": "Henri Charrière",
        "url":  "./images/Papillon.png",  
        "date": "05/07/23",
        "rating": "10",
        "review": "https://tomasmiskov.com/papillon.html",
    },
    {
        "name" : "Dying To Be Me",
        "author": "Anita Moorjani",
        "url":  "./images/Dying To Be Me.png",  
        "date": "31/07/23",
        "rating": "4",
        "review": "https://tomasmiskov.com/dying-to-be-me.html",
    },
    {
        "name" : "Anaximander",
        "author": "Carlo Rovelli",
        "url":  "./images/Anaximander.png",  
        "date": "19/08/23",
        "rating": "8.5",
        "review": "https://tomasmiskov.com/anaximander.html",
    },
    {
        "name" : "The Myth of Normal",
        "author": "Gabor Maté",
        "url":  "./images/The Myth of Normal.png",  
        "date": "15/09/23",
        "rating": "8",
        "review": "https://tomasmiskov.com/the-myth-of-normal.html",
    },
    {
        "name" : "Banco",
        "author": "Henri Charrière",
        "url":  "./images/Banco.png",  
        "date": "22/09/23",
        "rating": "9",
        "review": "https://tomasmiskov.com/banco.html",
    },
    {
        "name" : "The Shell Collector",
        "author": "Anthony Doerr",
        "url":  "./images/The Shell Collector.png",  
        "date": "05/10/23",
        "rating": "8",
        "review": "https://tomasmiskov.com/the-shell-collector.html",
    },
    {
        "name" : "A Mathematician's Apology",
        "author": "Godfrey Harold Hardy",
        "url":  "./images/A Mathematician's Apology.png",  
        "date": "08/10/23",
        "rating": "8",
        "review": "https://tomasmiskov.com/mathematicians-apology.html",
    },
    {
        "name" : "Tribes",
        "author": "Seth Godin",
        "url":  "./images/Tribes.png",  
        "date": "25/10/23",
        "rating": "6.5",
        "review": "https://tomasmiskov.com/tribes.html",
    },
    {
        "name" : "This Perfect Day",
        "author": "Ira Levin",
        "url":  "./images/This Perfect Day.png",  
        "date": "23/11/23",
        "rating": "8.5",
        "review": "https://tomasmiskov.com/this-perfect-day.html",
    },
    {
        "name" : "Endurance",
        "author": "Alfred Lansing",
        "url":  "./images/Endurance.png",  
        "date": "02/01/24",
        "rating": "9",
        "review": "https://tomasmiskov.com/endurance.html",
    },
    {
        "name" : "The Web of Life",
        "author": "John H. Storer",
        "url":  "./images/The Web of Life.png",  
        "date": "21/01/24",
        "rating": "9",
        "review": "https://tomasmiskov.com/the-web-of-life.html",
    },
    {
        "name" : "OPEN",
        "author": "Andre Agassi",
        "url":  "./images/OPEN.png",  
        "date": "10/02/24",
        "rating": "9",
        "review": "https://tomasmiskov.com/open.html",
    },
    {
        "name" : "The Solutions Are Already Here",
        "author": "Peter Gelderloos",
        "url":  "./images/Solutions Are Already Here.png",  
        "date": "04/04/24",
        "rating": "6.5",
        "review": "https://tomasmiskov.com/solutions-are-here.html",
    },
    {
        "name" : "Brave New World",
        "author": "Aldous Huxley",
        "url":  "./images/Brave New World.png",  
        "date": "04/14/24",
        "rating": "7",
        "review": "https://tomasmiskov.com/brave-new-world.html",
    },
    {
        "name" : "Brave New World Revisited",
        "author": "Aldous Huxley",
        "url":  "./images/Brave New World Revisited.png",  
        "date": "04/27/24",
        "rating": "9",
        "review": "https://tomasmiskov.com/brave-new-world-revisited.html",
    },
    {
        "name" : "To Kill a Mockingbird",
        "author": "Harper Lee",
        "url":  "./images/To Kill a Mockingbird.png",  
        "date": "05/13/24",
        "rating": "7",
        "review": "https://tomasmiskov.com/to-kill-a-mockingbird.html",
    },
    {
        "name" : "Thinking, Fast and Slow",
        "author": "Daniel Kahneman",
        "url":  "./images/Thinking Fast and Slow.png",  
        "date": "06/12/24",
        "rating": "10",
        "review": "https://tomasmiskov.com/thinking-fast-and-slow.html",
    },
    {
        "name" : "Exploration Fawcett: Journey to the Lost City of Z",
        "author": "Percy Fawcett",
        "url":  "./images/Exploration Fawcett.png",  
        "date": "07/08/24",
        "rating": "7.5",
        "review": "https://tomasmiskov.com/exploration-fawcett.html",
    },
    {
        "name" : "The Cell",
        "author": "Joshua Z. Rappoport",
        "url":  "./images/The Cell.png",  
        "date": "07/26/24",
        "rating": "7",
        "review": "https://tomasmiskov.com/the-cell.html",
    },
    {
        "name" : "Lord of the Flies",
        "author": "William Golding",
        "url":  "./images/Lord of the Flies.png",  
        "date": "08/05/24",
        "rating": "5",
        "review": "https://tomasmiskov.com/lord-of-flies.html",
    },
    {
        "name" : "The Book of Laughter and Forgetting",
        "author": "Milan Kundera",
        "url":  "./images/The Book of Laughter and Forgetting.png",  
        "date": "08/25/24",
        "rating": "7.5",
        "review": "https://tomasmiskov.com/book-of-laughter-and-forgetting.html",
    },
    {
        "name" : "The Blind Watchmaker",
        "author": "Richard Dawkins",
        "url":  "./images/The Blind Watchmaker.png",  
        "date": "09/27/24",
        "rating": "8",
        "review": "https://tomasmiskov.com/the-blind-watchmaker.html",
    },
    {
        "name" : "The Creative Act",
        "author": "Rick Rubin",
        "url":  "./images/The Creative Act.png",  
        "date": "10/13/24",
        "rating": "5",
        "review": "https://tomasmiskov.com/the-creative-act.html",
    },
    {
        "name" : "Man's Search for Meaning",
        "author": "Viktor E. Frankl",
        "url":  "./images/Man's Search for Meaning.png",  
        "date": "10/25/24",
        "rating": "8",
        "review": "https://tomasmiskov.com/mans-search-for-meaning.html",
    },
    {
        "name" : "Educated",
        "author": "Tara Westover",
        "url":  "./images/Educated.png",  
        "date": "11/13/24",
        "rating": "8",
        "review": "https://tomasmiskov.com/educated.html",
    },
    {
        "name" : "Entangled Life",
        "author": "Merlin Sheldrake",
        "url":  "./images/Entangled Life.png",  
        "date": "12/02/24",
        "rating": "8",
        "review": "https://tomasmiskov.com/entangled-life.html",
    },
    {
        "name" : "An Evil Cradling",
        "author": "Brian Keenan",
        "url":  "./images/An Evil Cradling.png",  
        "date": "20/02/24",
        "rating": "7.5",
        "review": "https://tomasmiskov.com/evil-cradling.html",
    },
    {
        "name" : "The Nature of Nature",
        "author": "Enric Sala",
        "url":  "./images/The Nature of Nature.png",  
        "date": "31/12/24",
        "rating": "10",
        "review": "https://tomasmiskov.com/nature-of-nature.html",
    },
    {
        "name" : "Love Triangle",
        "author": "Matt Parker",
        "url":  "./images/Love Triangle.png",  
        "date": "22/01/25",
        "rating": "8",
        "review": "https://tomasmiskov.com/love-triangle.html",
    }
]

data.sort((a, b) => a.author.localeCompare(b.author));